name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          outputs: |
            profile-3d-contrib/profile-green-animate.svg
            profile-3d-contrib/profile-green.svg
            profile-3d-contrib/profile-season-animate.svg
            profile-3d-contrib/profile-season.svg
            profile-3d-contrib/profile-south-season-animate.svg
            profile-3d-contrib/profile-south-season.svg
            profile-3d-contrib/profile-night-view.svg
            profile-3d-contrib/profile-night-green.svg
            profile-3d-contrib/profile-night-rainbow.svg
            profile-3d-contrib/profile-gitblock.svg
      - name: push profile-*.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
